import os
import pickle
import argparse
from pathlib import Path

import pandas as pd

from utils import load_edges


def graph_edges_metrics(edges_predicted: set, ground_truth: set) -> tuple[float, float]:
    """
    Calculates precision and recall for the predicted graph edges against the ground truth.

    Parameters
    ----------
    edges_predicted : set
        The set of edges predicted by a nearest neighbors graph method.
    ground_truth : set
        The set of edges from the reference consistency graph.

    Returns
    -------
    tuple[float, float]
        A tuple containing the precision and recall scores, in that order.
    """
    # Identifies true positives, false positives, and false negatives
    true_positives = edges_predicted & ground_truth
    false_positives = edges_predicted - ground_truth
    false_negatives = ground_truth - edges_predicted

    # Computes precision: proportion of predicted edges that are correct
    precision = len(true_positives) / (len(true_positives) + len(false_positives)) if (len(true_positives) + len(false_positives)) > 0 else 0

    # Computes recall: proportion of ground truth edges that were correctly predicted
    recall = len(true_positives) / (len(true_positives) + len(false_negatives)) if (len(true_positives) + len(false_negatives)) > 0 else 0

    return precision, recall


def compare_graphs(reference_folder: str, comparison_folder: str, method: str, output_dir: str) -> None:
    """
    Compares graphs from a reference folder (ground truth) with graphs from a comparison folder, calculating precision and recall.

    Parameters
    ----------
    reference_folder : str
        Path to the folder containing the ground truth graphs (reference).
    comparison_folder : str
        Path to the folder containing the graphs generated by dimensionality reduction methods.
    method : str
        The dimensionality reduction method associated with the comparison folder.
    output_dir : str
        Directory where the comparison results will be saved.

    Returns
    -------
    None
        The function saves a pickle file with the comparison results, including precision and recall for each graph pair.
    """
    
    # Lists and sorts files for structured and consistent comparisons
    reference_files = sorted(os.listdir(reference_folder))
    comparison_files = sorted(os.listdir(comparison_folder))
    
    # Ensures the output directory exists
    Path(output_dir).mkdir(parents=True, exist_ok=True)

    results = []

    # Iterates over each reference graph file
    for ref_file in reference_files:
        ref_edges = load_edges(reference_folder, ref_file)
        
        # Compares it with each file in the comparison folder
        for comp_file in comparison_files:
            comp_edges = load_edges(comparison_folder, comp_file)
            
            # Calculates precision and recall, then store the result
            precision, recall = graph_edges_metrics(comp_edges, ref_edges)
            results.append({
                "Reference Graph": ref_file,
                "Compared Graph": comp_file,
                "Precision": precision,
                "Recall": recall
            })

            print(f"Compared {ref_file} with {comp_file}: Precision={precision:.2f}, Recall={recall:.2f}")
    
    # Converts the results to a pandas DataFrame
    structured_results = pd.DataFrame(results)

    # Saves the results as a Parquet file
    results_file = os.path.join(output_dir, f"comparison_results_{method}.parquet")
    structured_results.to_parquet(results_file, index=False)

    print(f"Comparison results saved to {results_file}")



if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Obtains the paths to evaluate graph representations.")

    # Arguments for each folder
    parser.add_argument("--reference_folder", type=str, default="./GeneratedGraphs/Consistency", help="Directory for consistency graphs.")
    parser.add_argument("--pca_folder", type=str, default="./GeneratedGraphs/PCA", help="Directory for PCA graphs.")
    parser.add_argument("--tsne_folder", type=str, default="./GeneratedGraphs/TSNE", help="Directory for t-SNE graphs.")
    parser.add_argument("--umap_folder", type=str, default="./GeneratedGraphs/UMAP", help="Directory for UMAP graphs.")
    parser.add_argument("--output_dir", type=str, default="./EvaluationResults", help="Directory to save evaluation results.")

    args = parser.parse_args()

    # Accessing folder paths
    reference_folder = args.reference_folder
    pca_folder = args.pca_folder
    tsne_folder = args.tsne_folder
    umap_folder = args.umap_folder
    output_dir = args.output_dir

    # applying the comparsions and obtaining the results for each method against the reference (consistency graphs)
    compare_graphs(reference_folder, pca_folder, "PCA", output_dir)
    compare_graphs(reference_folder, tsne_folder, "TSNE", output_dir)
    compare_graphs(reference_folder, umap_folder, "UMAP", output_dir)
    print("Evaluation completed successfully", flush=True)

